## UNIR CSVs

### CARGA INICIAL: AÑOS 2010-2018.

Jupyter notebook permite ejecutar sentencias consola, anteponiendo signo de admiración. Los 9 archivos se situan en la misma carpeta que el notebook para que funcione.

In [1]:
#! copy *.csv madrid_unico.csv

### NOTA: en cargas posteriores (periodicidad anual) bastaría con saltarse este bloque e indicar el nombre del archivo correspondiente del año en el bloque siguiente "CARGA DATASET". Tambíen por supuesto se deberían comentar o eliminar las celdas del bloque correspondiente a "CORRECCIONES DEBIDAS A LA UNIÓN", ya que tal unión se produce solo en la carga inicial y no en las restantes cargas anuales.

## CARGA DATASET

### Carga

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [9]:
dfmadrid = pd.read_csv('./madrid_unico.csv', sep=';', encoding='latin1')
dfmadrid.head()

C:\Users\edurp\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
0,01/01/2010,DE 00:00 A 00:59,VIERNES,CHAMARTIN,CALLE DE CARTAGENA NUM ...,104,2010/135,NO,NO,SI,...,NO,NO,NO,1,COLISIÓN DOBLE,TURISMO,CONDUCTOR,HOMBRE,IL,DE 18 A 20 AÑOS
1,01/01/2010,DE 00:00 A 00:59,VIERNES,CHAMARTIN,CALLE DE CARTAGENA NUM ...,104,2010/135,NO,NO,SI,...,NO,NO,NO,1,COLISIÓN DOBLE,TURISMO,CONDUCTOR,HOMBRE,IL,DE 50 A 54 AÑOS
2,01/01/2010,DE 00:00 A 00:59,VIERNES,CHAMARTIN,CALLE DE CARTAGENA NUM ...,104,2010/135,NO,NO,SI,...,NO,NO,NO,1,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,HL,DE 40 A 44 AÑOS
3,01/01/2010,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200,2010/94,NO,NO,NO,...,NO,NO,NO,7,COLISIÓN MÚLTIPLE,NO ASIGNADO,VIAJERO,MUJER,HL,DE 25 A 29 AÑOS
4,01/01/2010,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200,2010/94,NO,NO,NO,...,NO,NO,NO,7,COLISIÓN MÚLTIPLE,NO ASIGNADO,VIAJERO,MUJER,HL,DE 30 A 34 ANOS

In [10]:
dfmadrid.dtypes

FECHA                 object
RANGO HORARIO         object
DIA SEMANA            object
DISTRITO              object
LUGAR ACCIDENTE       object
Nº                    object
Nº PARTE              object
CPFA Granizo          object
CPFA Hielo            object
CPFA Lluvia           object
CPFA Niebla           object
CPFA Seco             object
CPFA Nieve            object
CPSV Mojada           object
CPSV Aceite           object
CPSV Barro            object
CPSV Grava Suelta     object
CPSV Hielo            object
CPSV Seca Y Limpia    object
Nº VICTIMAS *         object
TIPO ACCIDENTE        object
Tipo Vehiculo         object
TIPO PERSONA          object
SEXO                  object
LESIVIDAD             object
Tramo Edad            object
dtype: object

In [11]:
dfmadrid.columns

Index(['FECHA', 'RANGO HORARIO', 'DIA SEMANA', 'DISTRITO', 'LUGAR ACCIDENTE',
       'Nº', 'Nº PARTE', 'CPFA Granizo', 'CPFA Hielo', 'CPFA Lluvia',
       'CPFA Niebla', 'CPFA Seco', 'CPFA Nieve', 'CPSV Mojada', 'CPSV Aceite',
       'CPSV Barro', 'CPSV Grava Suelta', 'CPSV Hielo', 'CPSV Seca Y Limpia',
       'Nº VICTIMAS *', 'TIPO ACCIDENTE', 'Tipo Vehiculo', 'TIPO PERSONA',
       'SEXO', 'LESIVIDAD', 'Tramo Edad'],
      dtype='object')

### CAMBIAR A NOMBRES APROPIADOS LAS COLUMNAS

In [15]:
dfmadrid.columns = ['FECHA', 'RANGO_HORARIO', 'DIA_SEMANA', 'DISTRITO', 'LUGAR_ACCIDENTE', 'NUM_CALLE', 'NUM_PARTE', \
                   'Granizo', 'Hielo', 'Lluvia','Niebla', 'Seco', 'Nieve', 'supf_Mojada', 'supf_Aceite', 'supf_Barro', \
                   'supf_Grava_Suelta', 'supf_Hielo', 'supf_Seca_Limpia', 'NUM_VICTIMAS', 'TIPO_ACCIDENTE', 'Tipo_Vehiculo', \
                   'TIPO_PERSONA', 'SEXO', 'LESIVIDAD', 'Tramo_Edad']

dfmadrid.tail()

,FECHA,RANGO_HORARIO,DIA_SEMANA,DISTRITO,LUGAR_ACCIDENTE,NUM_CALLE,NUM_PARTE,Granizo,Hielo,Lluvia,...,supf_Grava_Suelta,supf_Hielo,supf_Seca_Limpia,NUM_VICTIMAS,TIPO_ACCIDENTE,Tipo_Vehiculo,TIPO_PERSONA,SEXO,LESIVIDAD,Tramo_Edad
253002,31/12/2018,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0,2019/18,NO,NO,NO,...,NO,NO,SI,1,COLISIÓN DOBLE,AUTO-TAXI,CONDUCTOR,HOMBRE,IL,DE 40 A 44 AÑOS
253003,31/12/2018,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0,2019/53,NO,NO,NO,...,NO,NO,SI,1,OTRAS CAUSAS,TURISMO,CONDUCTOR,MUJER,IL,DE 21 A 24 AÑOS
253004,31/12/2018,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0,2019/53,NO,NO,NO,...,NO,NO,SI,1,OTRAS CAUSAS,TURISMO,CONDUCTOR,HOMBRE,HL,DE 50 A 54 AÑOS
253005,31/12/2018,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0,2019/53,NO,NO,NO,...,NO,NO,SI,1,OTRAS CAUSAS,TURISMO,CONDUCTOR,NO ASIGNADO,NO ASIGNADA,DESCONOCIDA
253006,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### CORRECCIONES DEBIDAS A LA UNION DE LOS ARCHIVOS CSV

Como vemos en la celda anterior al unir los archivos 'csv' se produjo una ultima línea (registro) errónea que eliminaremos.

In [18]:
dfmadrid.drop([253006],axis=0,inplace=True)
dfmadrid.tail()

,FECHA,RANGO_HORARIO,DIA_SEMANA,DISTRITO,LUGAR_ACCIDENTE,NUM_CALLE,NUM_PARTE,Granizo,Hielo,Lluvia,...,supf_Grava_Suelta,supf_Hielo,supf_Seca_Limpia,NUM_VICTIMAS,TIPO_ACCIDENTE,Tipo_Vehiculo,TIPO_PERSONA,SEXO,LESIVIDAD,Tramo_Edad
253001,31/12/2018,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0,2019/18,NO,NO,NO,...,NO,NO,SI,1,COLISIÓN DOBLE,TURISMO,VIAJERO,HOMBRE,IL,DE 30 A 34 ANOS
253002,31/12/2018,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0,2019/18,NO,NO,NO,...,NO,NO,SI,1,COLISIÓN DOBLE,AUTO-TAXI,CONDUCTOR,HOMBRE,IL,DE 40 A 44 AÑOS
253003,31/12/2018,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0,2019/53,NO,NO,NO,...,NO,NO,SI,1,OTRAS CAUSAS,TURISMO,CONDUCTOR,MUJER,IL,DE 21 A 24 AÑOS
253004,31/12/2018,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0,2019/53,NO,NO,NO,...,NO,NO,SI,1,OTRAS CAUSAS,TURISMO,CONDUCTOR,HOMBRE,HL,DE 50 A 54 AÑOS
253005,31/12/2018,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0,2019/53,NO,NO,NO,...,NO,NO,SI,1,OTRAS CAUSAS,TURISMO,CONDUCTOR,NO ASIGNADO,NO ASIGNADA,DESCONOCIDA

También encontraremos las cabeceras (nombre de los campos) de todos los archivos menos el primero como registros,  ya que los une tal cual. Simplemente eliminamos también esos registros. Los localizamos por coincidencia de valor del campo para cualquiera de ellos.

In [30]:
dfmadrid[dfmadrid.Granizo == 'CPFA Granizo']

,FECHA,RANGO_HORARIO,DIA_SEMANA,DISTRITO,LUGAR_ACCIDENTE,NUM_CALLE,NUM_PARTE,Granizo,Hielo,Lluvia,...,supf_Grava_Suelta,supf_Hielo,supf_Seca_Limpia,NUM_VICTIMAS,TIPO_ACCIDENTE,Tipo_Vehiculo,TIPO_PERSONA,SEXO,LESIVIDAD,Tramo_Edad
26578,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
53921,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
80904,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
107744,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
135712,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
163885,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
193087,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,Nº VICTIMAS *,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad
222883,FECHA,RANGO HORARIO,DIA SEMANA,DISTRITO,LUGAR ACCIDENTE,Nº,Nº PARTE,CPFA Granizo,CPFA Hielo,CPFA Lluvia,...,CPSV Grava Suelta,CPSV Hielo,CPSV Seca Y Limpia,* Nº VICTIMAS,TIPO ACCIDENTE,Tipo Vehiculo,TIPO PERSONA,SEXO,LESIVIDAD,Tramo Edad

In [33]:
dfmadrid.drop(dfmadrid[dfmadrid.Granizo == 'CPFA Granizo'].index, axis=0, inplace=True)

dfmadrid[['Granizo','Hielo','Lluvia','Niebla','Seco','Nieve','supf_Mojada','supf_Aceite','supf_Barro', \
         'supf_Grava_Suelta', 'supf_Hielo', 'supf_Seca_Limpia']].describe()

,Granizo,Hielo,Lluvia,Niebla,Seco,Nieve,supf_Mojada,supf_Aceite,supf_Barro,supf_Grava_Suelta,supf_Hielo,supf_Seca_Limpia
count,252998,252998,252998,252998,252998,252998,252998,252998,252998,252998,252998,252998
unique,2,2,2,2,2,2,2,2,2,2,2,2
top,NO,NO,NO,NO,SI,NO,NO,NO,NO,NO,NO,SI
freq,252964,252788,224626,252410,223743,252645,220421,252438,252794,252378,252639,218222

### CONVERSIÓN DE TIPOS

Pasamos a convertir los tipos de los campos (todos detectados inicialmente como Object) que no sean texto. En el caso de los campos relativos a las condiciones meteorológicas y de suelo aprovecharmos para codificarlas de booleano a número por mapeo.

In [50]:
conv_tipos = {'numero': ['NUM_CALLE','NUM_VICTIMAS'], 'fecha': ['FECHA'], \
              'booleano': ['Granizo','Hielo','Lluvia','Niebla','Seco','Nieve','supf_Mojada','supf_Aceite','supf_Barro', \
                          'supf_Grava_Suelta', 'supf_Hielo', 'supf_Seca_Limpia']}

conv_bool = {'NO': 0, 'SI':1}
  

for tipo, columnas in conv_tipos.items():
      
    if tipo == 'numero':
        
        for col in columnas:
            dfmadrid[col] = pd.to_numeric(dfmadrid[col])
            
    if tipo == 'fecha':
        for col in columnas:
            dfmadrid[col] = pd.to_datetime(dfmadrid[col], dayfirst=True, format="%d/%m/%Y")
            
    if tipo == 'booleano':
        for col in columnas:
            dfmadrid[col] = dfmadrid[col].map(conv_bool)
            
            
dfmadrid.dtypes

FECHA                datetime64[ns]
RANGO_HORARIO                object
DIA_SEMANA                   object
DISTRITO                     object
LUGAR_ACCIDENTE              object
NUM_CALLE                   float64
NUM_PARTE                    object
Granizo                       int64
Hielo                         int64
Lluvia                        int64
Niebla                        int64
Seco                          int64
Nieve                         int64
supf_Mojada                   int64
supf_Aceite                   int64
supf_Barro                    int64
supf_Grava_Suelta             int64
supf_Hielo                    int64
supf_Seca_Limpia              int64
NUM_VICTIMAS                float64
TIPO_ACCIDENTE               object
Tipo_Vehiculo                object
TIPO_PERSONA                 object
SEXO                         object
LESIVIDAD                    object
Tramo_Edad                   object
dtype: object

In [51]:
dfmadrid.head(10)

,FECHA,RANGO_HORARIO,DIA_SEMANA,DISTRITO,LUGAR_ACCIDENTE,NUM_CALLE,NUM_PARTE,Granizo,Hielo,Lluvia,...,supf_Grava_Suelta,supf_Hielo,supf_Seca_Limpia,NUM_VICTIMAS,TIPO_ACCIDENTE,Tipo_Vehiculo,TIPO_PERSONA,SEXO,LESIVIDAD,Tramo_Edad
0,2010-01-01,DE 00:00 A 00:59,VIERNES,CHAMARTIN,CALLE DE CARTAGENA NUM ...,104.0,2010/135,0,0,1,...,0,0,0,1.0,COLISIÓN DOBLE,TURISMO,CONDUCTOR,HOMBRE,IL,DE 18 A 20 AÑOS
1,2010-01-01,DE 00:00 A 00:59,VIERNES,CHAMARTIN,CALLE DE CARTAGENA NUM ...,104.0,2010/135,0,0,1,...,0,0,0,1.0,COLISIÓN DOBLE,TURISMO,CONDUCTOR,HOMBRE,IL,DE 50 A 54 AÑOS
2,2010-01-01,DE 00:00 A 00:59,VIERNES,CHAMARTIN,CALLE DE CARTAGENA NUM ...,104.0,2010/135,0,0,1,...,0,0,0,1.0,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,HL,DE 40 A 44 AÑOS
3,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,NO ASIGNADO,VIAJERO,MUJER,HL,DE 25 A 29 AÑOS
4,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,NO ASIGNADO,VIAJERO,MUJER,HL,DE 30 A 34 ANOS
5,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,NO ASIGNADO,VIAJERO,MUJER,HL,DE 25 A 29 AÑOS
6,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,NO ASIGNADO,VIAJERO,MUJER,HL,DE 25 A 29 AÑOS
7,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,TURISMO,CONDUCTOR,HOMBRE,IL,DE 25 A 29 AÑOS
8,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,TURISMO,CONDUCTOR,MUJER,HL,DE 25 A 29 AÑOS
9,2010-01-01,DE 1:00 A 1:59,VIERNES,PUENTE DE VALLECAS,AUTOVIA M-30 CALZADA 2 KM. ...,10200.0,2010/94,0,0,0,...,0,0,0,7.0,COLISIÓN MÚLTIPLE,TURISMO,VIAJERO,MUJER,HL,DE 21 A 24 AÑOS

In [52]:
dfmadrid.tail(10)

,FECHA,RANGO_HORARIO,DIA_SEMANA,DISTRITO,LUGAR_ACCIDENTE,NUM_CALLE,NUM_PARTE,Granizo,Hielo,Lluvia,...,supf_Grava_Suelta,supf_Hielo,supf_Seca_Limpia,NUM_VICTIMAS,TIPO_ACCIDENTE,Tipo_Vehiculo,TIPO_PERSONA,SEXO,LESIVIDAD,Tramo_Edad
252996,2018-12-31,DE 21:00 A 21:59,LUNES,CENTRO,CALLE DE VILLANUEVA - PASEO DE RECOLETOS ...,0.0,2019/32,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,AUTO-TAXI,CONDUCTOR,HOMBRE,IL,DE 30 A 34 ANOS
252997,2018-12-31,DE 21:00 A 21:59,LUNES,CENTRO,CALLE DE VILLANUEVA - PASEO DE RECOLETOS ...,0.0,2019/32,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,AUTO-TAXI,VIAJERO,MUJER,IL,DE 25 A 29 AÑOS
252998,2018-12-31,DE 21:00 A 21:59,LUNES,CENTRO,CALLE DE VILLANUEVA - PASEO DE RECOLETOS ...,0.0,2019/32,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,AUTO-TAXI,VIAJERO,MUJER,HL,DE 21 A 24 AÑOS
252999,2018-12-31,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0.0,2019/18,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,TURISMO,CONDUCTOR,HOMBRE,HL,DE 45 A 49 AÑOS
253000,2018-12-31,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0.0,2019/18,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,TURISMO,VIAJERO,MUJER,IL,DE 25 A 29 AÑOS
253001,2018-12-31,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0.0,2019/18,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,TURISMO,VIAJERO,HOMBRE,IL,DE 30 A 34 ANOS
253002,2018-12-31,DE 21:00 A 21:59,LUNES,SALAMANCA,CALLE DE VELAZQUEZ - CALLE DE VILLANUEVA ...,0.0,2019/18,0,0,0,...,0,0,1,1.0,COLISIÓN DOBLE,AUTO-TAXI,CONDUCTOR,HOMBRE,IL,DE 40 A 44 AÑOS
253003,2018-12-31,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0.0,2019/53,0,0,0,...,0,0,1,1.0,OTRAS CAUSAS,TURISMO,CONDUCTOR,MUJER,IL,DE 21 A 24 AÑOS
253004,2018-12-31,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0.0,2019/53,0,0,0,...,0,0,1,1.0,OTRAS CAUSAS,TURISMO,CONDUCTOR,HOMBRE,HL,DE 50 A 54 AÑOS
253005,2018-12-31,DE 23:00 A 23:59,LUNES,HORTALEZA,CALLE DE JOAQUIN FERNANDEZ LEIVA - CALLE DE SI...,0.0,2019/53,0,0,0,...,0,0,1,1.0,OTRAS CAUSAS,TURISMO,CONDUCTOR,NO ASIGNADO,NO ASIGNADA,DESCONOCIDA

### AGRUPAMOS VARIABLES POR TIPO PARA UN MEJOR PROCESAMIENTO.

In [53]:
var_texto = ['RANGO_HORARIO', 'DIA_SEMANA', 'DISTRITO', 'LUGAR_ACCIDENTE','NUM_PARTE','TIPO_ACCIDENTE', 'Tipo_Vehiculo', \
             'TIPO_PERSONA', 'SEXO', 'LESIVIDAD','Tramo_Edad']

var_num = ['NUM_CALLE','NUM_VICTIMAS']

var_bool = ['Granizo','Hielo','Lluvia','Niebla','Seco','Nieve','supf_Mojada','supf_Aceite','supf_Barro', \
            'supf_Grava_Suelta', 'supf_Hielo', 'supf_Seca_Limpia']

### ELIMINACIÓN ESPACIOS EN BLANCO ADICIONALES INNECESARIOS (AL PRINCIPIO Y AL FINAL) EN CAMPOS TEXTO.

En la **inspección ocular previa (como texto plano)** de los archivos 'csv' se detectaron espacios en blanco superfluos en los campos texto. Pasamos a eliminarlos.

In [72]:
print(list(dfmadrid.DISTRITO.head()))

['CHAMARTIN                     ', 'CHAMARTIN                     ', 'CHAMARTIN                     ', 'PUENTE DE VALLECAS            ', 'PUENTE DE VALLECAS            ']

In [ ]:
for col in var_texto:
    dfmadrid[col] = dfmadrid[col].str.strip()

In [74]:
print(list(dfmadrid.DISTRITO.head()))

['CHAMARTIN', 'CHAMARTIN', 'CHAMARTIN', 'PUENTE DE VALLECAS', 'PUENTE DE VALLECAS']

In [75]:
print(list(dfmadrid.LUGAR_ACCIDENTE.head()))

['CALLE DE CARTAGENA NUM', 'CALLE DE CARTAGENA NUM', 'CALLE DE CARTAGENA NUM', 'AUTOVIA  M-30 CALZADA 2 KM.', 'AUTOVIA  M-30 CALZADA 2 KM.']

### GUARDAMOS FINALMENTE ARCHIVO CON TODOS LOS AÑOS DE LA CARGA INICIAL, CON NOMBRE Y TIPO DE LOS CAMPOS ADECUADO

In [ ]:
dfmadrid.to_csv('./madrid_accid.csv',sep=',',header=True,index=False,encoding='latin1')

Partiremos de este archivo para el preprocesamiento necesario.